version: '3.8'
services: 
  mongodb:
    image: 'mongo'
    volumes: 
      - data:/data/db
   # environment:
     # - MONGODB_USERNAME=chida \
     # MONGODB_USERNAME: chida \
      #- MONGODB_PASSWORD=secret \
    env_file:
      - ./env/mongo.env
    
volumes:
  data: 
  

