version: '3.8'
services: 
  mongodb:
    image: 'mongo'
    volumes: 
      - data:/data/db
   # environment:
     # - MONGODB_USERNAME=chida \
     # MONGODB_USERNAME: chida \
      #- MONGODB_PASSWORD=secret \
    env_file:
      - ./env/mongo.env

  backend: 
    build: ./backend
    ports:
     - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
      
    
volumes:
  data: 
  logs:


